---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: vikas-v1
  labels:
    app: test
    test: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      test: v1
  template:
    metadata:
      labels:
        test: v1
        version: v0.0.1
    spec:
      containers:
      - name: vikas
        image: vikas027/site-counter
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        ports:
        - containerPort: 80
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: vikas-v2
  labels:
    app: test
    test: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      test: v2
  template:
    metadata:
      labels:
        test: v2
        version: v0.0.3
    spec:
      containers:
      - name: vikas
        image: vikas027/site-counter
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        env:
        - name: SHOW_IP
          value: "false"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vikas-v1
  namespace: default
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 80
  selector:
    test: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: vikas-v2
  namespace: default
  labels:
    app: test
spec:
  ports:
  - name: http
    port: 80
  selector:
    test: v2
  type: ClusterIP
